version: '2'
services:
  web:
    build: .
    image: wtl_service_web
    env_file: .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/webapp/.google_config.json
    links:
      - redis_worker
      - redis_db
    ports:
      - "80:5000"
    tty: true
    volumes:
      - ./webapp:/opt/webapp
      - ./models:/opt/models
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    command: gunicorn wsgi --bind=0.0.0.0:5000 --timeout=6000 --workers=4
    # Or to use the Flask built-in server for testing: 
    # command: python3 app.py
  redis_worker:
    image: redis:alpine
    ports:
      - "6379:6379"
  redis_db:
    image: redis:alpine
    ports:
      - "6380:6379"
  worker:
    image: wtl_service_web:latest
    env_file: .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/webapp/.google_config.json
    volumes:
      - ./webapp:/opt/webapp
    command: python3 worker.py

